server:
  port: 8888
  servlet:
    context-path: /huhu

spring:
  output:
    ansi:
      enabled: always

logging:
  file:
    name: huhu.log  # 日志文件绝对路径及名称
  level:
    root: info

bot:
  super-users: [1942422015, 2412125282]



